---
all:
  hosts:
    R1:
      ansible_host: 192.168.110.1/24
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_network_cli_ssh_type: paramiko
    ansible_user: cisco
    ansible_ssh_pass: cisc
    ansible_password: cisc
    ansible_port: 22
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisc
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
