---
- name: Configure Router R1
  hosts: R1
  gather_facts: no
  tasks:
    - name: Configure Interface GE0/10
      ios_config:
        lines:
          - ip address 176.54.0.1 255.255.255.252
          - no shutdown
        parents: interface GE0/10
...